; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:esp32-s2-devkitm-1]

[env:esp32-s3-devkitc-1]
platform = espressif32@6.10.0 ; or latest
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_port = /dev/cu.usbmodem101
lib_deps = 
	robtillaart/PCA9635@^0.6.0
; build_src_filter = 
;     +<*>
;     +<**/*.cpp>
;     -<test_pca.cpp>
; 	-<test_midi.cpp>
;build_src_filter = 
;    +<test_pca.cpp>
build_src_filter = 
    +<test_midi.cpp>

; add these when you're wanting to boot into USB OTG
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3
;    -DCONFIG_TINYUSB_DEBUG_LEVEL=2

; Monitor settings for better debugging
monitor_filters = 
    esp32_exception_decoder
    time


; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; lib_deps= lathoub/BLE-MIDI@^2.2, robtillaart/PCA9635@^0.6.0